<?php
$urlpatterns = [
 array(
   'path'=>'/login/',
   'file'=>'mpm/auth/login.php',
   'name'=>'login'
   ),
 array(
   'path'=>'/signup/',
   'file'=>'mpm/auth/signup.php',
   'name'=>'signup'
   ),
  array(
   'path'=>'/logout/',
   'file'=>'mpm/auth/logout.php',
   'name'=>'logout'
   ),
  array(
   'path'=>'/404/',
   'file'=>'404.php',
   'name'=>'404'
   ),
  array(
   'path'=>'/permission-denied/',
   'file'=>'permission_denied.php',
   'name'=>'permission_denied'
   ),
  array(
   'path'=>'/[a-zA-Z]*[.]php',
   'file'=>'blog/blog_list.php',
   'name'=>'index'
  ),
  array(
    'path'=>"/blog_detail/(?P<id>\d+)/",
    'file'=>'blog/blog_detail.php',
    'name'=>'blog_detail'
  ),
  array(
    'path'=>"/blog_create/",
    'file'=>'blog/blog_create.php',
    'name'=>'blog_create'
  ),
  array(
    'path'=>"/blog_edit/(?P<id>\d+)/",
    'file'=>'blog/blog_edit.php',
    'name'=>'blog_edit'
  ),
  array(
    'path'=>"/blog_delete/(?P<id>\d+)/",
    'file'=>'blog/blog_delete.php',
    'name'=>'blog_delete'
  ),
  array(
    'path'=>'',
    'file'=>'blog/blog_list.php',
    'name'=>'home'
  ),
];
